name: harvester
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=20
  - fsspec
  - requests
  - s3fs>=0.5
  - dask
  - loguru
  - pandas
  - progressbar2
  - typer
  - zarr
  - xarray
  - lxml
  - gspread==3.6
  - fastparquet
  - pygithub
  - siphon
  - prefect>=0.14
  - rechunker
  - pip:
      - git+https://github.com/ooi-data/ooi-harvester.git@main