name: Update from template

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  TEMPLATE_REPO: ooi-data/stream_template

jobs:
  template-update:
    name: Template Update
    runs-on: ubuntu-20.04
    if: github.repository != 'ooi-data/stream_template'
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
      - name: Install update-template
        run: npm install -g update-template
      - name: Run update template
        run: npx update-template https://github.com/${{ env.TEMPLATE_REPO }}
      - name: Commit changes
        id: auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updating repository from template
      - name: "Run if changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: echo "Changes was detected!"
      - name: "Run if no changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'false'
        run: echo "No changes detected!"
